version: '3'

services:

  database:
    build: db/
    image: mysql:5.6
    command: --disable-partition-engine-check
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
      - ENV MYSQL_DATABASE=pleysteven
      - ENV MYSQL_USER=root
    ports:
      - 3306:3306

  gallery:
    build: ./
    depends_on:
      - 'database'
    restart: on-failure
    ports: 
      - '3005:3005'

