version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11
      - image: circleci/mysql:5.7.22
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_ROOT_HOST=%

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/photo-gallery

    steps:
      - checkout

      # Download and cache dependencies
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            
      # - restore_cache:
          # keys:
          # - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          # - v1-dependencies-
      # - run: sudo npm install -y npm 
      # - save_cache:
          # paths:
            # - node_modules
          # key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo apt install -y mysql-client

      - run: mysql -h 127.0.0.1 -u root < ./db/schema.sql

      - run: sudo apt install -y express

      - run:
          command: node ./server/server.js
          background: true

      - run: npm test