version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11
      - image: circleci/mysql:5.7.22
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_ROOT_PASSWORD: 'password'
          - MYSQL_DATABASE: pley

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: sudo npm install mysql-client
      # - run: sudo apt-get install mysql-server

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mysql -h 127.0.0.1 -u root -p < ./db/schema.sql
      - run: password

      - run:
          command: node ./server/server.js
          background: true

      - run: npm test