version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11
        environment:
          - DB_CONNECTION: mysql
          - DB_HOST: 127.0.0.1
          - DB_PORT: 3005
          - DB_DATABASE: pley
          - DB_USERNAME: root
          - DB_PASSWORD: password
      - image: circleci/mysql:5.7.22
        environment:
          - MYSQL_ROOT_HOST: "root"
          - MYSQL_ROOT_PASSWORD: password

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm install -y npm 
      - run: sudo apt install -y mysql-client

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run: mysql -h 127.0.0.1 -u root -p < ./db/schema.sql
      - run: mysql -h$DB_HOST -u$DB_USERNAME -p$DB_PASSWORD $DB_DATABASE < ./db/schema.sql #Example: /home/circleci/<YOUR REPOSITORY>/<YOUR DATABASE FILE>


      - run:
          command: node ./server/server.js
          background: true

      - run: npm test