-- mysql.server start
-- mysql -u root < schema.sql

DROP DATABASE IF EXISTS pleySteven;

CREATE DATABASE pleySteven;

USE pleySteven;


-- CREATE TABLE users (
-- 	id INT NOT NULL AUTO_INCREMENT,
-- 	username varchar(100) NOT NULL,
-- 	profile_picture varchar(100),
-- 	location varchar(50),  
-- 	PRIMARY KEY(id)
-- );

CREATE TABLE restaurants (
	id int NOT NULL AUTO_INCREMENT,
	name varchar(50) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE pictures (
	id int NOT NULL AUTO_INCREMENT,
	url varchar(200) NOT NULL,
	helpful int NOT NULL,
	not_helpful int NOT NULL,
	restaurant_id int NOT NULL,
	-- users_id int NOT NULL,
	PRIMARY KEY (id),
	-- FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

INSERT INTO restaurants (name) VALUES ("Gogi Time");
INSERT INTO restaurants (name) VALUES ("Boba Guys");
INSERT INTO restaurants (name) VALUES ("Chipotle");
INSERT INTO restaurants (name) VALUES ("Fork & Spoon");
INSERT INTO restaurants (name) VALUES ("Halal Guys");
INSERT INTO restaurants (name) VALUES ("EighTea");
INSERT INTO restaurants (name) VALUES ("Burger King");
INSERT INTO restaurants (name) VALUES ("In-n-Out");
INSERT INTO restaurants (name) VALUES ("Popeyes");
INSERT INTO restaurants (name) VALUES ("Tu Lan");
INSERT INTO restaurants (name) VALUES ("KFC");
INSERT INTO restaurants (name) VALUES ("Chick-fil-a");
INSERT INTO restaurants (name) VALUES ("Blind Tiger");
INSERT INTO restaurants (name) VALUES ("Wendy's");
INSERT INTO restaurants (name) VALUES ("A&W");
INSERT INTO restaurants (name) VALUES ("Rooster & Rice");
INSERT INTO restaurants (name) VALUES ("Shakewell");
INSERT INTO restaurants (name) VALUES ("Flipside");
INSERT INTO restaurants (name) VALUES ("Urban Tavern");
INSERT INTO restaurants (name) VALUES ("707 Sutter");
INSERT INTO restaurants (name) VALUES ("Momofuku");
INSERT INTO restaurants (name) VALUES ("Roaring Fork");
INSERT INTO restaurants (name) VALUES ("Ippudo");
INSERT INTO restaurants (name) VALUES ("The Melt");
INSERT INTO restaurants (name) VALUES ("BunMee");
INSERT INTO restaurants (name) VALUES ("Pei Wei");
INSERT INTO restaurants (name) VALUES ("The Cavalier");
INSERT INTO restaurants (name) VALUES ("Dirty Habit");
INSERT INTO restaurants (name) VALUES ("Lin Jia Asian Kitchen");
INSERT INTO restaurants (name) VALUES ("Colonial Donuts");
INSERT INTO restaurants (name) VALUES ("Oakland Kosher Foods");
INSERT INTO restaurants (name) VALUES ("Rolling Dunes");
INSERT INTO restaurants (name) VALUES ("Grand Lake Kitchen");
INSERT INTO restaurants (name) VALUES ("Soba Ichi");
INSERT INTO restaurants (name) VALUES ("Proposition Chicken");
INSERT INTO restaurants (name) VALUES ("Qi Dumpling Lounge");
INSERT INTO restaurants (name) VALUES ("Warren's Webpack Bananza");
INSERT INTO restaurants (name) VALUES ("Arizmendi Bakery");
INSERT INTO restaurants (name) VALUES ("The Star on Grand");
INSERT INTO restaurants (name) VALUES ("Holy Land Restuarant");
INSERT INTO restaurants (name) VALUES ("Cheese Steak Shop");
INSERT INTO restaurants (name) VALUES ("Anson's Handsome Hamburgers");
INSERT INTO restaurants (name) VALUES ("Belcampo Restuarant & Butcher Shop");
INSERT INTO restaurants (name) VALUES ("Daily Grill");
INSERT INTO restaurants (name) VALUES ("Morton's The Steakhouse");
INSERT INTO restaurants (name) VALUES ("The Mark");
INSERT INTO restaurants (name) VALUES ("California Pizza Kitchen");
INSERT INTO restaurants (name) VALUES ("Ikaros Greek Restuarant");
INSERT INTO restaurants (name) VALUES ("Modigliani Cafe");
INSERT INTO restaurants (name) VALUES ("JJ Burger");
INSERT INTO restaurants (name) VALUES ("Sliver");
INSERT INTO restaurants (name) VALUES ("Lakeshore Cafe");
INSERT INTO restaurants (name) VALUES ("Belly");
INSERT INTO restaurants (name) VALUES ("Lovely's");
INSERT INTO restaurants (name) VALUES ("Mua");
INSERT INTO restaurants (name) VALUES ("Flavor of India");
INSERT INTO restaurants (name) VALUES ("Dosirak Shop");
INSERT INTO restaurants (name) VALUES ("Super Duper Burgers");
INSERT INTO restaurants (name) VALUES ("Hancook");
INSERT INTO restaurants (name) VALUES ("Chan's Kitchen");
INSERT INTO restaurants (name) VALUES ("Steven's Slow Today Deli");
INSERT INTO restaurants (name) VALUES ("Aisle 5");
INSERT INTO restaurants (name) VALUES ("CANA Cuban Parlor & Cafe");
INSERT INTO restaurants (name) VALUES ("Homeroom");
INSERT INTO restaurants (name) VALUES ("Justin's Koolaid Bar");
INSERT INTO restaurants (name) VALUES ("CHICA Oakland");
INSERT INTO restaurants (name) VALUES ("Penrose");
INSERT INTO restaurants (name) VALUES ("Mockingbird");
INSERT INTO restaurants (name) VALUES ("Wally's Cafe");
INSERT INTO restaurants (name) VALUES ("Orchid Pavillion Cafe");
INSERT INTO restaurants (name) VALUES ("Fogo de Chao");
INSERT INTO restaurants (name) VALUES ("The Grove");
INSERT INTO restaurants (name) VALUES ("Michael's Romantic Bulgogi Beef");
INSERT INTO restaurants (name) VALUES ("Belotti Ristorante");
INSERT INTO restaurants (name) VALUES ("Tacolicious");
INSERT INTO restaurants (name) VALUES ("The Hog's Apothecary");
INSERT INTO restaurants (name) VALUES ("Tim Ho Wan");
INSERT INTO restaurants (name) VALUES ("Postino's");
INSERT INTO restaurants (name) VALUES ("The Melting Pot");
INSERT INTO restaurants (name) VALUES ("Rubio's");
INSERT INTO restaurants (name) VALUES ("Bonchon");
INSERT INTO restaurants (name) VALUES ("MOD Pizza");
INSERT INTO restaurants (name) VALUES ("Wingstop");
INSERT INTO restaurants (name) VALUES ("Tempest");
INSERT INTO restaurants (name) VALUES ("Playland");
INSERT INTO restaurants (name) VALUES ("Raven");
INSERT INTO restaurants (name) VALUES ("Temple");
INSERT INTO restaurants (name) VALUES ("Hawthorne");
INSERT INTO restaurants (name) VALUES ("The Yellow Submarine");
INSERT INTO restaurants (name) VALUES ("Subway");
INSERT INTO restaurants (name) VALUES ("Umami Burger");
INSERT INTO restaurants (name) VALUES ("Asian Box");
INSERT INTO restaurants (name) VALUES ("Hopscotch");
INSERT INTO restaurants (name) VALUES ("Shogun Japanese Sushi");
INSERT INTO restaurants (name) VALUES ("Shane is Li's bestfriend");
INSERT INTO restaurants (name) VALUES ("Champa Garden");
INSERT INTO restaurants (name) VALUES ("Southern Cafe");
INSERT INTO restaurants (name) VALUES ("Jong Ga House");
INSERT INTO restaurants (name) VALUES ("Sidebar Oaktown");
INSERT INTO restaurants (name) VALUES ("Mua");

INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/19.jpg", 3, 3, 1);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/70.jpg", 9, 9, 1);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/50.jpg", 6, 2, 1);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/4.jpg", 7, 7, 2);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/18.jpg", 9, 4, 2);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/32.jpg", 3, 3, 2);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/22.jpg", 13, 11, 3);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/51.jpg", 4, 13, 3);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/79.jpg", 2, 3, 3);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/17.jpg", 5, 14, 4);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/1.jpg", 5, 1, 4);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/34.jpg", 14, 2, 4);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 1, 13, 5);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/19.jpg", 4, 9, 5);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/65.jpg", 4, 6, 5);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/12.jpg", 11, 11, 6);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/21.jpg", 9, 13, 6);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/12.jpg", 2, 7, 6);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/55.jpg", 11, 3, 7);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/54.jpg", 8, 2, 7);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/53.jpg", 4, 0, 7);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/42.jpg", 13, 12, 8);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/47.jpg", 3, 5, 8);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/27.jpg", 1, 12, 8);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/35.jpg", 13, 10, 9);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/65.jpg", 1, 11, 9);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/60.jpg", 4, 0, 9);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/25.jpg", 6, 0, 10);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/9.jpg", 10, 6, 10);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/77.jpg", 13, 4, 10);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/11.jpg", 10, 13, 11);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/52.jpg", 9, 0, 11);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/31.jpg", 2, 4, 11);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/15.jpeg", 5, 4, 12);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/12.jpg", 2, 5, 12);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/57.jpg", 10, 5, 12);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/27.jpg", 3, 14, 13);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/43.jpg", 5, 1, 13);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/43.jpg", 11, 11, 13);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 3, 0, 14);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/24.jpg", 1, 13, 14);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/10.jpg", 2, 12, 14);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/18.jpg", 12, 12, 15);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/34.jpg", 6, 13, 15);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 3, 12, 15);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/65.jpg", 8, 10, 16);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/10.jpg", 2, 4, 16);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/12.jpg", 6, 13, 16);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/72.jpg", 10, 1, 17);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/11.jpg", 5, 10, 17);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 8, 8, 17);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/39.jpg", 12, 5, 18);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/34.jpg", 13, 2, 18);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/66.jpg", 4, 12, 18);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/25.jpg", 14, 13, 19);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/21.jpg", 3, 4, 19);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/5.jpg", 6, 4, 19);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/16.jpeg", 12, 9, 20);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 12, 4, 20);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/81.png", 5, 10, 20);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/4.jpg", 11, 4, 21);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/45.jpg", 4, 6, 21);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/2.jpg", 14, 12, 21);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 10, 4, 22);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/63.jpg", 4, 1, 22);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/41.jpg", 9, 3, 22);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 6, 12, 23);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/47.jpg", 12, 12, 23);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/36.jpg", 13, 0, 23);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/23.jpg", 5, 11, 24);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/18.jpg", 0, 6, 24);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/26.jpg", 11, 8, 24);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/34.jpg", 11, 8, 25);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/7.jpg", 3, 6, 25);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/47.jpg", 14, 12, 25);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 12, 10, 26);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/52.jpg", 5, 1, 26);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 0, 7, 26);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/51.jpg", 2, 4, 27);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/19.jpg", 2, 5, 27);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/15.jpeg", 12, 6, 27);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/39.jpg", 9, 9, 28);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/64.jpg", 14, 0, 28);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/55.jpg", 1, 13, 28);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/45.jpg", 9, 4, 29);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/45.jpg", 5, 5, 29);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/54.jpg", 5, 6, 29);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/45.jpg", 2, 9, 30);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/42.jpg", 13, 8, 30);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 6, 5, 30);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/12.jpg", 4, 13, 31);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 8, 11, 31);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/78.jpg", 11, 0, 31);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/77.jpg", 5, 0, 32);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/33.jpg", 1, 11, 32);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/37.jpg", 5, 3, 32);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/34.jpg", 2, 4, 33);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/57.jpg", 6, 3, 33);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/69.jpg", 14, 9, 33);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/46.jpg", 12, 9, 34);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/30.jpg", 12, 7, 34);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/21.jpg", 0, 10, 34);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/33.jpg", 12, 7, 35);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/18.jpg", 12, 1, 35);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/71.jpg", 13, 9, 35);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/14.jpg", 1, 9, 36);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/40.jpg", 13, 13, 36);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/26.jpg", 9, 12, 36);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/63.jpg", 14, 1, 37);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/38.jpg", 8, 14, 37);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/48.jpg", 5, 11, 37);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/71.jpg", 5, 9, 38);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/49.jpg", 13, 9, 38);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/69.jpg", 11, 10, 38);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/52.jpg", 9, 14, 39);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/25.jpg", 0, 5, 39);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/20.jpg", 11, 6, 39);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/13.jpg", 14, 11, 40);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/25.jpg", 7, 8, 40);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/64.jpg", 8, 12, 40);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/24.jpg", 9, 11, 41);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/40.jpg", 4, 5, 41);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/22.jpg", 8, 7, 41);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 10, 11, 42);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/47.jpg", 0, 12, 42);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/56.jpg", 7, 2, 42);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/37.jpg", 0, 2, 43);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/40.jpg", 5, 4, 43);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/16.jpeg", 2, 5, 43);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/55.jpg", 14, 3, 44);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/15.jpeg", 3, 9, 44);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/4.jpg", 1, 6, 44);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/11.jpg", 12, 8, 45);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/42.jpg", 7, 4, 45);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/5.jpg", 6, 6, 45);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 2, 10, 46);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/7.jpg", 6, 13, 46);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/71.jpg", 11, 13, 46);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 0, 2, 47);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/22.jpg", 14, 6, 47);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/64.jpg", 0, 1, 47);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/2.jpg", 9, 4, 48);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/51.jpg", 6, 9, 48);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/79.jpg", 7, 2, 48);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 2, 13, 49);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/53.jpg", 8, 4, 49);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/79.jpg", 2, 3, 49);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/73.jpg", 7, 8, 50);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/78.jpg", 0, 13, 50);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/39.jpg", 2, 14, 50);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/23.jpg", 8, 13, 51);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/57.jpg", 11, 12, 51);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 6, 3, 51);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/31.jpg", 7, 6, 52);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/40.jpg", 11, 2, 52);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/28.jpg", 6, 3, 52);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/41.jpg", 4, 11, 53);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/78.jpg", 3, 1, 53);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/1.jpg", 14, 8, 53);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/70.jpg", 1, 10, 54);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/7.jpg", 6, 1, 54);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/79.jpg", 14, 13, 54);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/62.jpg", 11, 4, 55);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/79.jpg", 3, 14, 55);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/30.jpg", 13, 6, 55);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/58.jpg", 13, 12, 56);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/24.jpg", 9, 0, 56);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/61.jpg", 14, 4, 56);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/68.jpg", 9, 3, 57);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/41.jpg", 13, 12, 57);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/58.jpg", 3, 3, 57);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/54.jpg", 1, 10, 58);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/27.jpg", 9, 3, 58);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/56.jpg", 5, 12, 58);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/29.jpg", 1, 12, 59);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/16.jpeg", 5, 14, 59);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/26.jpg", 13, 7, 59);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/77.jpg", 9, 5, 60);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/58.jpg", 7, 8, 60);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/78.jpg", 8, 2, 60);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/35.jpg", 5, 3, 61);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/31.jpg", 0, 5, 61);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/33.jpg", 6, 9, 61);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/52.jpg", 4, 11, 62);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/52.jpg", 7, 11, 62);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/15.jpeg", 12, 5, 62);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/16.jpeg", 11, 0, 63);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 0, 13, 63);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/73.jpg", 1, 7, 63);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/64.jpg", 14, 0, 64);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/73.jpg", 11, 5, 64);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/11.jpg", 11, 11, 64);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/54.jpg", 11, 11, 65);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/38.jpg", 11, 14, 65);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/63.jpg", 10, 1, 65);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/26.jpg", 10, 11, 66);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/5.jpg", 0, 10, 66);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/27.jpg", 0, 14, 66);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 12, 2, 67);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/63.jpg", 0, 11, 67);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/71.jpg", 5, 11, 67);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/64.jpg", 5, 7, 68);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/68.jpg", 2, 11, 68);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/45.jpg", 8, 14, 68);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/34.jpg", 6, 8, 69);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/10.jpg", 9, 3, 69);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/73.jpg", 14, 14, 69);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/48.jpg", 10, 13, 70);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/32.jpg", 6, 11, 70);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/35.jpg", 9, 12, 70);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/68.jpg", 9, 6, 71);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/39.jpg", 7, 3, 71);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/1.jpg", 0, 10, 71);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/27.jpg", 5, 2, 72);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 13, 7, 72);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/59.jpg", 9, 10, 72);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/59.jpg", 11, 9, 73);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/67.jpg", 3, 2, 73);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/61.jpg", 11, 0, 73);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/73.jpg", 11, 14, 74);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/36.jpg", 14, 1, 74);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/40.jpg", 11, 0, 74);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/60.jpg", 14, 4, 75);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/79.jpg", 4, 4, 75);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/80.jpg", 9, 11, 75);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/80.jpg", 0, 11, 76);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/59.jpg", 9, 6, 76);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 1, 0, 76);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/12.jpg", 10, 6, 77);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 0, 7, 77);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/73.jpg", 5, 0, 77);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/22.jpg", 2, 13, 78);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/23.jpg", 12, 9, 78);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/5.jpg", 8, 1, 78);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/29.jpg", 3, 7, 79);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/37.jpg", 13, 3, 79);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/36.jpg", 2, 9, 79);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/58.jpg", 6, 5, 80);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/29.jpg", 12, 13, 80);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 7, 5, 80);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/18.jpg", 4, 4, 81);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/71.jpg", 12, 10, 81);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 1, 9, 81);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/12.jpg", 14, 6, 82);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/43.jpg", 3, 6, 82);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/62.jpg", 13, 2, 82);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/63.jpg", 9, 3, 83);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 1, 3, 83);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/47.jpg", 9, 8, 83);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 8, 4, 84);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/66.jpg", 2, 2, 84);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/13.jpg", 10, 5, 84);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/73.jpg", 10, 9, 85);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/58.jpg", 13, 6, 85);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/10.jpg", 7, 9, 85);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/33.jpg", 9, 1, 86);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/50.jpg", 6, 13, 86);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/7.jpg", 9, 3, 86);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/32.jpg", 11, 3, 87);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/60.jpg", 1, 10, 87);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/65.jpg", 4, 9, 87);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/25.jpg", 7, 10, 88);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/14.jpg", 11, 4, 88);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/3.jpg", 3, 9, 88);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/10.jpg", 12, 14, 89);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/4.jpg", 9, 5, 89);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 14, 13, 89);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/35.jpg", 14, 7, 90);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/20.jpg", 4, 14, 90);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/4.jpg", 10, 4, 90);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/62.jpg", 3, 14, 91);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 14, 4, 91);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/37.jpg", 10, 10, 91);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/9.jpg", 14, 13, 92);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/57.jpg", 12, 1, 92);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/80.jpg", 9, 6, 92);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/29.jpg", 7, 9, 93);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/45.jpg", 14, 11, 93);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/11.jpg", 0, 2, 93);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 2, 5, 94);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/53.jpg", 10, 10, 94);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/43.jpg", 10, 11, 94);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/27.jpg", 9, 5, 95);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/18.jpg", 2, 14, 95);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/48.jpg", 10, 2, 95);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/65.jpg", 6, 9, 96);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/40.jpg", 13, 0, 96);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/33.jpg", 5, 6, 96);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/53.jpg", 7, 14, 97);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/69.jpg", 11, 7, 97);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/58.jpg", 2, 7, 97);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/56.jpg", 0, 2, 98);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 12, 0, 98);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/45.jpg", 9, 6, 98);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/20.jpg", 5, 5, 99);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/48.jpg", 4, 7, 99);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/76.jpg", 12, 11, 99);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/6.jpg", 4, 10, 100);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/75.jpg", 8, 13, 100);
INSERT INTO pictures (url, helpful, not_helpful, restaurant_id) VALUES ("https://s3-us-west-1.amazonaws.com/pley-land/20.jpg", 14, 14, 100);